### ISSUE TITLE
Console have spam when i starting trmenu v2 with essentials

### ISSUE THREAD

**Issue by abczyx22** [TrMenu/TrMenu#162]
check it pls:
https://pastebin.com/0Cb8VgR3

**Comment by Bkm016** [comment]
十分抱歉，这个问题是因为 Essentials 的 checkForcedMetrics 方法出现了意料之外的错误，请您向 Essentials 相关开发者反馈，我们的统计完全遵循 BStats 的数据上传协议。
 
Sorry, this problem is caused by an unexpected error in the checkForcedMetrics method of Essentials. Please provide feedback to the relevant developers of Essentials. Our statistics follow the BStats data upload protocol.

https://github.com/TabooLib/TabooLib/blob/a1d7ce12c6baf94c0a34a7e979ebcadaebcec5be/src/main/scala/io/izzel/taboolib/metrics/BStats.java#L95
